version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2
  slack: circleci/slack@4.1.3

workflows:
  build_and_upload:
    jobs:
      - build-intrigue-ident:
          context:
              - Build Context (Low Security)
      - security-scan-intrigue-ident:
          requires:
            - build-intrigue-ident
          context:
              - SecurityTesting Context
          filters:
              branches:
                only:
                  - main
      - deploy-intrigue-ident:
          requires:
            - build-intrigue-ident
          context:
              - Deploy Context (High Security) 
          filters:
              branches:
                only:
                  - main 
jobs:
  build-intrigue-ident:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          BUNDLER_VERSION: 2.1.4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Install dependencies & run specs 
          command:  | 
            sudo apt-get -y install git-core
            gem update --system
            gem install bundler:2.1.4
            bundle install
            bundle exec rspec spec/* 
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Job *${CIRCLE_JOB}* in branch `<< pipeline.git.branch >>` by committer ${CIRCLE_USERNAME} has *failed* :warning:. View job <${CIRCLE_BUILD_URL}|here>."
                  }
                }
              ]
            }
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Job *${CIRCLE_JOB}* in branch `<< pipeline.git.branch >>` by committer ${CIRCLE_USERNAME} successful :white_check_mark:. View job <${CIRCLE_BUILD_URL}|here>."
                  }
                }
              ]
            }
  security-scan-intrigue-ident:
    docker:
      - image: circleci/ruby:2.7.2-browsers
    steps:
      - checkout
      - run:
          name: Run whitesource
          command:  | 
            bundle install
            curl -LJO https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar
            echo Unified Agent downloaded successfully
            java -jar wss-unified-agent.jar -project intrigue-ident -d ./
  deploy-intrigue-ident:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          BUNDLER_VERSION: 2.1.4
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Build gem and upload to gemfury
          command:  | 
            gem build intrigue-ident.gemspec
            ls *.gem | xargs -I{} curl --silent -F package=@{} https://${GEMFURY_TOKEN}@push.fury.io/intrigueio --stderr - | tee curl.out
            if grep -E "already exists|unauthorized|denied|error" curl.out; then exit -1; fi
      - slack/notify:
          event: fail
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "@here Job *${CIRCLE_JOB}* in branch `<< pipeline.git.branch >>` by committer ${CIRCLE_USERNAME} has *failed* :warning:. View job <${CIRCLE_BUILD_URL}|here>."
                  }
                }
              ]
            }
      - slack/notify:
          event: pass
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "Job *${CIRCLE_JOB}* in branch `<< pipeline.git.branch >>` by committer ${CIRCLE_USERNAME} successful :white_check_mark:. View job <${CIRCLE_BUILD_URL}|here>."
                  }
                }
              ]
            }